org.gradle.jvmargs=-Xmx2048M -XX:MaxMetaspaceSize=512M
org.gradle.parallel=false
org.gradle.java.home=C:\\Users\\ADMIN\\java\\17.0.13+11
android.useAndroidX=true
android.enableJetifier=false
android.newDsl=false
# This builtInKotlin flag was added automatically by Flutter migrator
android.builtInKotlin=false
